/**
 * 资源数据配置文件
 * 包含所有学习资源的分类和详细信息
 */
const resourcesData = {
  // 分类定义
  categories: [
    { id: "all", name: "全部资源" },
    { id: "basics", name: "计算机基础" },
    { id: "languages", name: "编程语言" },
    { id: "frontend", name: "前端开发" },
    { id: "backend", name: "后端开发" },
    { id: "ai", name: "人工智能" },
    { id: "tools", name: "开发工具" },
    { id: "interview", name: "求职面试" },
    { id: "community", name: "技术社区" },
  ],
  // 资源列表
  resources: [
    // --- 计算机基础 ---
    {
      id: "cs-notes",
      category: "basics",
      title: "CS-Notes",
      desc: "技术面试必备基础知识、LeetCode、计算机操作系统、计算机网络、系统设计。",
      link: "https://github.com/CyC2018/CS-Notes",
      iconClass: "fab fa-github",
      tags: ["面试", "基础", "GitHub Star 100k+"],
      recommendReason: "可能是GitHub上最全的计算机基础面试指南，适合查漏补缺。",
      level: "入门/进阶",
    },
    {
      id: "hello-algo",
      category: "basics",
      title: "Hello 算法",
      desc: "动画图解、一键运行的数据结构与算法教程。",
      link: "https://www.hello-algo.com/",
      iconClass: "fas fa-cubes",
      tags: ["算法", "数据结构", "图解"],
      recommendReason: "非常适合新手的算法入门书，图解清晰，代码支持多种语言。",
      level: "入门",
    },
    {
      id: "mooc",
      category: "basics",
      title: "中国大学MOOC",
      desc: "汇集中国顶尖高校的计算机专业课程，如翁恺C语言、陈越数据结构等。",
      link: "https://www.icourse163.org/category/computer",
      iconClass: "fas fa-graduation-cap",
      tags: ["视频课程", "名校", "系统学习"],
      recommendReason: "科班出身必修课，弥补学校教学质量差异的最佳途径。",
      level: "入门",
    },
    {
      id: "bilibili",
      category: "basics",
      title: "Bilibili",
      desc: "国内知名的视频弹幕网站，拥有海量高质量的编程教学视频。",
      link: "https://www.bilibili.com/",
      iconClass: "fab fa-bilibili",
      tags: ["视频", "教程", "免费"],
      recommendReason: "众所周知，B站是一个学习网站。",
      level: "全阶段",
    },

    // --- 编程语言 ---
    {
      id: "liaoxuefeng",
      category: "languages",
      title: "廖雪峰教程",
      desc: "Python, Java, Git, JavaScript 等编程语言的入门教程。",
      link: "https://www.liaoxuefeng.com/",
      iconClass: "fas fa-book-open",
      tags: ["Python", "Java", "入门"],
      recommendReason: "通俗易懂，适合零基础快速上手一门新语言。",
      level: "入门",
    },
    {
      id: "javaguide",
      category: "languages",
      title: "JavaGuide",
      desc: "一份涵盖大部分 Java 程序员所需要掌握的核心知识。",
      link: "https://javaguide.cn/",
      iconClass: "fab fa-java",
      tags: ["Java", "面试", "后端"],
      recommendReason: "Java后端开发者的“圣经”，面试突击神器。",
      level: "进阶",
    },
    {
      id: "go-tour",
      category: "languages",
      title: "Go 语言之旅",
      desc: "Go 语言官方提供的交互式教程。",
      link: "https://tour.go-zh.org/welcome/1",
      iconClass: "fas fa-code",
      tags: ["Go", "官方", "交互式"],
      recommendReason: "学习Go语言最正统的入门方式，边学边练。",
      level: "入门",
    },
    {
      id: "typescript",
      category: "languages",
      title: "TypeScript",
      desc: "TypeScript 是具有类型语法的 JavaScript。",
      link: "https://www.typescriptlang.org/zh/",
      iconClass: "fab fa-js",
      tags: ["前端", "类型安全", "微软"],
      recommendReason: "前端进阶必备，大型项目标配。",
      level: "进阶",
    },
    {
      id: "rust",
      category: "languages",
      title: "Rust",
      desc: "一门赋予每个人构建可靠且高效软件能力的语言。",
      link: "https://www.rust-lang.org/zh-CN/",
      iconClass: "fas fa-cogs",
      tags: ["系统编程", "高性能", "安全"],
      recommendReason:
        "连续多年被评为最受开发者喜爱的语言，虽然学习曲线陡峭但值得。",
      level: "高阶",
    },

    // --- 前端开发 ---
    {
      id: "mdn",
      category: "frontend",
      title: "MDN Web Docs",
      desc: "Web 技术权威文档，涵盖 HTML, CSS, JavaScript, API 等。",
      link: "https://developer.mozilla.org/zh-CN/",
      iconClass: "fab fa-firefox-browser",
      tags: ["权威", "文档", "基础"],
      recommendReason: "前端开发的字典，遇到不懂的属性查它准没错。",
      level: "全阶段",
    },
    {
      id: "vue",
      category: "frontend",
      title: "Vue.js",
      desc: "渐进式 JavaScript 框架，易学易用，国内企业应用广泛。",
      link: "https://cn.vuejs.org/",
      iconClass: "fab fa-vuejs",
      tags: ["框架", "国产友好", "文档优秀"],
      recommendReason: "文档写得最好的框架之一，国内就业必备技能。",
      level: "进阶",
    },
    {
      id: "react",
      category: "frontend",
      title: "React",
      desc: "用于构建 Web 和原生用户界面的库，生态极其丰富。",
      link: "https://react.dev/",
      iconClass: "fab fa-react",
      tags: ["框架", "大厂", "生态丰富"],
      recommendReason: "全球最流行的前端库，进大厂通常需要掌握。",
      level: "进阶",
    },
    {
      id: "nextjs",
      category: "frontend",
      title: "Next.js",
      desc: "React 框架，用于构建全栈 Web 应用程序。",
      link: "https://nextjs.org/",
      iconClass: "fas fa-layer-group",
      tags: ["React", "SSR", "全栈"],
      recommendReason: "React生态中最流行的服务端渲染框架。",
      level: "进阶",
    },
    {
      id: "tailwindcss",
      category: "frontend",
      title: "Tailwind CSS",
      desc: "只需 HTML 即可快速构建现代网站。",
      link: "https://tailwindcss.com/",
      iconClass: "fas fa-wind",
      tags: ["CSS", "原子化", "高效"],
      recommendReason: "写CSS不再痛苦，一旦上手就回不去了。",
      level: "进阶",
    },
    {
      id: "vite",
      category: "frontend",
      title: "Vite",
      desc: "下一代前端开发与构建工具。",
      link: "https://cn.vitejs.dev/",
      iconClass: "fas fa-bolt",
      tags: ["构建工具", "极速", "尤雨溪"],
      recommendReason: "快！非常快！开发体验极佳。",
      level: "进阶",
    },

    // --- 后端开发 ---
    {
      id: "spring",
      category: "backend",
      title: "Spring",
      desc: "Java 应用开发框架，Spring Boot 让开发变得简单。",
      link: "https://spring.io/",
      iconClass: "fas fa-leaf",
      tags: ["Java", "框架", "企业级"],
      recommendReason: "Java后端开发的工业标准，不学Spring等于没学Java Web。",
      level: "进阶",
    },
    {
      id: "redis",
      category: "backend",
      title: "Redis",
      desc: "开源的内存数据结构存储，用作数据库、缓存和消息代理。",
      link: "https://redis.io/",
      iconClass: "fas fa-database",
      tags: ["缓存", "NoSQL", "高性能"],
      recommendReason: "高性能系统必不可少的组件，面试高频考点。",
      level: "进阶",
    },
    {
      id: "docker",
      category: "backend",
      title: "Docker",
      desc: "开发人员和系统管理员使用容器开发、部署和运行应用程序的平台。",
      link: "https://www.docker.com/",
      iconClass: "fab fa-docker",
      tags: ["容器", "运维", "部署"],
      recommendReason: "解决“在我电脑上能跑”问题的终极方案，微服务基础。",
      level: "进阶",
    },
    {
      id: "mysql",
      category: "backend",
      title: "MySQL",
      desc: "最流行的开源关系型数据库管理系统。",
      link: "https://dev.mysql.com/doc/",
      iconClass: "fas fa-database",
      tags: ["数据库", "SQL", "必备"],
      recommendReason: "后端开发的基石，数据存储的首选。",
      level: "入门",
    },
    {
      id: "kubernetes",
      category: "backend",
      title: "Kubernetes",
      desc: "生产级别的容器编排系统。",
      link: "https://kubernetes.io/zh-cn/",
      iconClass: "fas fa-dharmachakra",
      tags: ["K8s", "云原生", "容器编排"],
      recommendReason: "云原生时代的操作系统，大厂运维和后端必备。",
      level: "高阶",
    },
    {
      id: "nginx",
      category: "backend",
      title: "Nginx",
      desc: "高性能的 HTTP 和反向代理服务器。",
      link: "https://nginx.org/en/",
      iconClass: "fas fa-server",
      tags: ["服务器", "代理", "负载均衡"],
      recommendReason: "高性能Web服务器，反向代理和负载均衡的神器。",
      level: "进阶",
    },

    // --- 人工智能 ---
    {
      id: "pytorch",
      category: "ai",
      title: "PyTorch",
      desc: "开源机器学习框架，加速从研究原型到生产部署的过程。",
      link: "https://pytorch.org/",
      iconClass: "fas fa-fire",
      tags: ["深度学习", "框架", "学术界"],
      recommendReason: "目前学术界最流行的深度学习框架，上手简单，调试方便。",
      level: "进阶",
    },
    {
      id: "huggingface",
      category: "ai",
      title: "Hugging Face",
      desc: "AI 社区，构建、训练和部署最先进的模型。",
      link: "https://huggingface.co/",
      iconClass: "fas fa-robot",
      tags: ["模型库", "NLP", "开源"],
      recommendReason: "AI领域的GitHub，海量预训练模型直接调用。",
      level: "进阶",
    },
    {
      id: "kaggle",
      category: "ai",
      title: "Kaggle",
      desc: "全球最大的数据科学社区和竞赛平台。",
      link: "https://www.kaggle.com/",
      iconClass: "fab fa-kaggle",
      tags: ["竞赛", "数据集", "实战"],
      recommendReason: "通过实战竞赛提升数据科学能力，还有免费GPU可用。",
      level: "进阶",
    },
    {
      id: "tensorflow",
      category: "ai",
      title: "TensorFlow",
      desc: "一个端到端的开源机器学习平台。",
      link: "https://www.tensorflow.org/",
      iconClass: "fas fa-brain",
      tags: ["Google", "深度学习", "工业界"],
      recommendReason: "Google出品，工业界应用广泛，部署能力强。",
      level: "进阶",
    },
    {
      id: "openai",
      category: "ai",
      title: "OpenAI API",
      desc: "构建下一代应用程序的 AI 模型接口。",
      link: "https://platform.openai.com/docs/introduction",
      iconClass: "fas fa-microchip",
      tags: ["LLM", "GPT", "API"],
      recommendReason: "目前最强大的大模型API，开发AI应用的首选。",
      level: "进阶",
    },
    {
      id: "langchain",
      category: "ai",
      title: "LangChain",
      desc: "用于开发由语言模型驱动的应用程序的框架。",
      link: "https://python.langchain.com/docs/get_started/introduction",
      iconClass: "fas fa-link",
      tags: ["LLM", "框架", "应用开发"],
      recommendReason: "大模型应用开发的胶水层，快速构建AI应用。",
      level: "进阶",
    },

    // --- 开发工具 ---
    {
      id: "vscode",
      category: "tools",
      title: "VS Code",
      desc: "重新定义代码编辑，免费、开源、跨平台。",
      link: "https://code.visualstudio.com/",
      iconClass: "fas fa-code",
      tags: ["编辑器", "微软", "插件丰富"],
      recommendReason: "宇宙第一编辑器，几乎支持所有语言，插件生态无敌。",
      level: "全阶段",
    },
    {
      id: "git",
      category: "tools",
      title: "Git",
      desc: "免费开源的分布式版本控制系统。",
      link: "https://git-scm.com/",
      iconClass: "fab fa-git-alt",
      tags: ["版本控制", "协作", "必备"],
      recommendReason: "团队协作的基石，不会Git寸步难行。",
      level: "入门",
    },
    {
      id: "typora",
      category: "tools",
      title: "Typora",
      desc: "所见即所得的 Markdown 编辑器，极致简洁。",
      link: "https://typora.io/",
      iconClass: "fas fa-pen-nib",
      tags: ["Markdown", "写作", "笔记"],
      recommendReason: "写技术博客、记笔记的神器，体验极佳。",
      level: "全阶段",
    },
    {
      id: "postman",
      category: "tools",
      title: "Postman",
      desc: "用于构建和使用 API 的 API 平台。",
      link: "https://www.postman.com/",
      iconClass: "fas fa-paper-plane",
      tags: ["API", "测试", "调试"],
      recommendReason: "后端开发调试接口的必备神器。",
      level: "进阶",
    },
    {
      id: "idea",
      category: "tools",
      title: "IntelliJ IDEA",
      desc: "Java 和 Kotlin 的首选 IDE。",
      link: "https://www.jetbrains.com/idea/",
      iconClass: "fab fa-java",
      tags: ["IDE", "Java", "智能"],
      recommendReason: "最好的Java IDE，智能提示和重构功能极其强大。",
      level: "进阶",
    },
    {
      id: "figma",
      category: "tools",
      title: "Figma",
      desc: "用于界面设计的协作界面设计工具。",
      link: "https://www.figma.com/",
      iconClass: "fab fa-figma",
      tags: ["设计", "UI/UX", "协作"],
      recommendReason: "前端开发和设计师协作的标准工具。",
      level: "入门",
    },

    // --- 求职面试 ---
    {
      id: "leetcode",
      category: "interview",
      title: "LeetCode",
      desc: "全球极客挚爱的技术成长平台，海量算法题库。",
      link: "https://leetcode.cn/",
      iconClass: "fas fa-code",
      tags: ["刷题", "算法", "大厂"],
      recommendReason: "想进大厂？刷它！每天一道题，offer不用愁。",
      level: "进阶",
    },
    {
      id: "nowcoder",
      category: "interview",
      title: "牛客网",
      desc: "求职之前，先上牛客。笔试题库、面试经验、内推机会。",
      link: "https://www.nowcoder.com/",
      iconClass: "fas fa-bullseye",
      tags: ["校招", "面经", "笔试"],
      recommendReason: "国内校招信息最全的平台，看面经避坑必备。",
      level: "就业",
    },
    {
      id: "boss",
      category: "interview",
      title: "Boss直聘",
      desc: "找工作，直接跟老板谈。",
      link: "https://www.zhipin.com/",
      iconClass: "fas fa-user-tie",
      tags: ["招聘", "求职", "沟通"],
      recommendReason: "目前活跃度较高的招聘平台，回复率相对较好。",
      level: "就业",
    },
    {
      id: "codetop",
      category: "interview",
      title: "CodeTop",
      desc: "汇总各大互联网公司面试中出现的算法题。",
      link: "https://codetop.cc/home",
      iconClass: "fas fa-list-ol",
      tags: ["面试", "高频", "算法"],
      recommendReason: "按公司和频率刷题，效率极高，面试突击必备。",
      level: "就业",
    },

    // --- 技术社区 ---
    {
      id: "juejin",
      category: "community",
      title: "掘金",
      desc: "帮助开发者成长的社区，技术文章质量较高。",
      link: "https://juejin.cn/",
      iconClass: "fas fa-layer-group",
      tags: ["社区", "前端", "分享"],
      recommendReason: "国内目前氛围较好的技术社区，前端资源尤为丰富。",
      level: "全阶段",
    },
    {
      id: "v2ex",
      category: "community",
      title: "V2EX",
      desc: "一个关于分享和探索的地方，程序员聚集地。",
      link: "https://www.v2ex.com/",
      iconClass: "fab fa-vimeo-v",
      tags: ["论坛", "极客", "讨论"],
      recommendReason: "很多独立开发者和技术大牛潜水，讨论话题比较前沿。",
      level: "全阶段",
    },
    {
      id: "github",
      category: "community",
      title: "GitHub",
      desc: "世界最大的开源代码托管平台。",
      link: "https://github.com/",
      iconClass: "fab fa-github",
      tags: ["开源", "代码", "社交"],
      recommendReason: "全球最大的同性交友网站（误），程序员的简历。",
      level: "全阶段",
    },
    {
      id: "stackoverflow",
      category: "community",
      title: "Stack Overflow",
      desc: "全球最大的开发者问答社区。",
      link: "https://stackoverflow.com/",
      iconClass: "fab fa-stack-overflow",
      tags: ["问答", "全球", "解决问题"],
      recommendReason: "遇到报错搜它，99%的问题都能找到答案。",
      level: "全阶段",
    },
    {
      id: "segmentfault",
      category: "community",
      title: "SegmentFault",
      desc: "中国领先的开发者技术社区。",
      link: "https://segmentfault.com/",
      iconClass: "fas fa-comments",
      tags: ["问答", "社区", "中文"],
      recommendReason: "中文版的Stack Overflow，国内技术交流的好去处。",
      level: "全阶段",
    },
  ],
};
