/**
 * 工具数据配置文件
 * 包含所有实用工具的分类和详细信息
 */
const toolsData = {
  // 分类定义
  categories: [
    { id: "all", name: "全部法器" },
    { id: "system", name: "系统增强" },
    { id: "efficiency", name: "效率办公" },
    { id: "dev", name: "开发辅助" },
    { id: "design", name: "设计图像" },
    { id: "media", name: "影音媒体" },
    { id: "online", name: "在线神器" },
  ],
  // 资源列表
  resources: [
    // --- 系统增强 ---
    {
      id: "powertoys",
      category: "system",
      title: "PowerToys",
      desc: "微软官方出品的系统增强工具集，含取色器、分屏、键盘映射等实用功能。",
      link: "https://github.com/microsoft/PowerToys",
      iconClass: "fab fa-microsoft",
      tags: ["微软", "系统", "开源"],
      recommendReason:
        "Windows用户必装神器，功能强大且免费，极大提升系统易用性。",
      level: "必备",
    },
    {
      id: "everything",
      category: "system",
      title: "Everything",
      desc: "Windows 上最快的文件搜索工具，毫秒级响应。",
      link: "https://www.voidtools.com/",
      iconClass: "fas fa-search",
      tags: ["搜索", "极速", "轻量"],
      recommendReason: "秒杀Windows自带搜索，找文件快到飞起。",
      level: "必备",
    },
    {
      id: "geek",
      category: "system",
      title: "Geek Uninstaller",
      desc: "轻量级软件卸载工具，强力清除残留文件和注册表。",
      link: "https://geekuninstaller.com/",
      iconClass: "fas fa-trash-alt",
      tags: ["卸载", "清理", "绿色"],
      recommendReason: "软件卸载不干净？用它！体积小巧，无需安装。",
      level: "实用",
    },
    {
      id: "7zip",
      category: "system",
      title: "7-Zip",
      desc: "免费开源的压缩解压软件，支持多种格式，压缩率高。",
      link: "https://www.7-zip.org/",
      iconClass: "fas fa-box-open",
      tags: ["压缩", "开源", "免费"],
      recommendReason: "最纯粹的压缩软件，无广告，功能强大。",
      level: "必备",
    },
    {
      id: "dism",
      category: "system",
      title: "Dism++",
      desc: "Windows 系统精简、优化、清理工具。",
      link: "https://github.com/Chuyu-Team/Dism-Multi-language",
      iconClass: "fas fa-tools",
      tags: ["优化", "清理", "系统"],
      recommendReason: "最懂Windows的优化工具，比各种卫士管家靠谱得多。",
      level: "进阶",
    },

    // --- 效率办公 ---
    {
      id: "snipaste",
      category: "efficiency",
      title: "Snipaste",
      desc: "截图+贴图神器，F1截图，F3贴图，支持像素级精准控制。",
      link: "https://www.snipaste.com/",
      iconClass: "fas fa-cut",
      tags: ["截图", "贴图", "生产力"],
      recommendReason:
        "用过就回不去的截图工具，贴图功能是写代码/写文档的神技。",
      level: "必备",
    },
    {
      id: "notion",
      category: "efficiency",
      title: "Notion",
      desc: "All-in-one 笔记、文档、任务管理工具。",
      link: "https://www.notion.so/",
      iconClass: "fas fa-book",
      tags: ["笔记", "协作", "数据库"],
      recommendReason: "颜值即正义，功能极其强大，适合构建个人知识库。",
      level: "热门",
    },
    {
      id: "obsidian",
      category: "efficiency",
      title: "Obsidian",
      desc: "基于本地 Markdown 文件的知识库工具，支持双向链接。",
      link: "https://obsidian.md/",
      iconClass: "fas fa-gem",
      tags: ["笔记", "本地", "双链"],
      recommendReason: "数据掌握在自己手中，插件生态丰富，适合深度知识管理。",
      level: "进阶",
    },
    {
      id: "utools",
      category: "efficiency",
      title: "uTools",
      desc: "新一代效率工具平台，通过插件扩展功能，呼之即来用完即走。",
      link: "https://u.tools/",
      iconClass: "fas fa-keyboard",
      tags: ["启动器", "插件", "效率"],
      recommendReason: "国产良心工具，Alt+Space呼出，几乎能做任何事。",
      level: "神器",
    },
    {
      id: "idm",
      category: "efficiency",
      title: "IDM",
      desc: "Internet Download Manager，Windows 上最强的下载工具。",
      link: "https://www.internetdownloadmanager.com/",
      iconClass: "fas fa-download",
      tags: ["下载", "加速", "多线程"],
      recommendReason: "下载速度提升5倍，支持嗅探网页视频，下载神器。",
      level: "必备",
    },

    // --- 开发辅助 ---
    {
      id: "postman",
      category: "dev",
      title: "Postman",
      desc: "API 开发协作平台，用于构建和使用 API。",
      link: "https://www.postman.com/",
      iconClass: "fas fa-paper-plane",
      tags: ["API", "调试", "后端"],
      recommendReason: "后端开发调试接口的必备神器，功能全面。",
      level: "必备",
    },
    {
      id: "terminal",
      category: "dev",
      title: "Windows Terminal",
      desc: "微软推出的现代化终端工具，支持多标签、自定义主题。",
      link: "https://github.com/microsoft/terminal",
      iconClass: "fas fa-terminal",
      tags: ["终端", "命令行", "微软"],
      recommendReason: "Windows上最好用的终端，颜值高，配置灵活。",
      level: "必备",
    },
    {
      id: "jsoncn",
      category: "dev",
      title: "JSON.cn",
      desc: "在线 JSON 解析、格式化、校验工具。",
      link: "https://www.json.cn/",
      iconClass: "fas fa-code",
      tags: ["JSON", "格式化", "在线"],
      recommendReason: "老牌JSON工具，简单好用，解析速度快。",
      level: "常用",
    },
    {
      id: "regexr",
      category: "dev",
      title: "RegExr",
      desc: "在线正则表达式测试工具，提供实时匹配和解释。",
      link: "https://regexr.com/",
      iconClass: "fas fa-registered",
      tags: ["正则", "测试", "学习"],
      recommendReason: "写正则不再头秃，实时反馈匹配结果，还有详细解释。",
      level: "实用",
    },
    {
      id: "switchhosts",
      category: "dev",
      title: "SwitchHosts",
      desc: "Hosts 文件管理工具，快速切换 Hosts 方案。",
      link: "https://github.com/oldj/SwitchHosts",
      iconClass: "fas fa-network-wired",
      tags: ["网络", "Hosts", "开发"],
      recommendReason: "开发环境切换域名的好帮手，支持远程Hosts。",
      level: "实用",
    },

    // --- 设计图像 ---
    {
      id: "figma",
      category: "design",
      title: "Figma",
      desc: "基于浏览器的协作界面设计工具。",
      link: "https://www.figma.com/",
      iconClass: "fab fa-figma",
      tags: ["设计", "UI", "协作"],
      recommendReason: "目前最流行的UI设计工具，跨平台，协作体验极佳。",
      level: "热门",
    },
    {
      id: "tinypng",
      category: "design",
      title: "TinyPNG",
      desc: "智能 WebP, PNG 和 JPEG 图片压缩工具。",
      link: "https://tinypng.com/",
      iconClass: "fas fa-compress-arrows-alt",
      tags: ["图片", "压缩", "在线"],
      recommendReason: "压缩率极高且几乎不损画质，前端优化图片必备。",
      level: "常用",
    },
    {
      id: "excalidraw",
      category: "design",
      title: "Excalidraw",
      desc: "手绘风格的虚拟白板工具，适合画架构图、流程图。",
      link: "https://excalidraw.com/",
      iconClass: "fas fa-pen-fancy",
      tags: ["绘图", "白板", "手绘风"],
      recommendReason: "画出来的图非常有格调，操作简单，支持协作。",
      level: "有趣",
    },
    {
      id: "carbon",
      category: "design",
      title: "Carbon",
      desc: "生成漂亮的代码图片，适合分享到社交媒体。",
      link: "https://carbon.now.sh/",
      iconClass: "fas fa-image",
      tags: ["代码", "图片", "分享"],
      recommendReason: "让你的代码截图瞬间高大上，多种主题可选。",
      level: "装逼",
    },

    // --- 影音媒体 ---
    {
      id: "potplayer",
      category: "media",
      title: "PotPlayer",
      desc: "Windows 上最强大的本地视频播放器。",
      link: "https://potplayer.daum.net/",
      iconClass: "fas fa-play-circle",
      tags: ["播放器", "全能", "高清"],
      recommendReason: "解码能力强，启动快，界面简洁，几乎支持所有格式。",
      level: "必备",
    },
    {
      id: "screen-to-gif",
      category: "media",
      title: "ScreenToGif",
      desc: "轻量级 GIF 录制、编辑工具。",
      link: "https://www.screentogif.com/",
      iconClass: "fas fa-video",
      tags: ["录屏", "GIF", "开源"],
      recommendReason: "录制GIF演示的神器，自带强大的编辑器。",
      level: "实用",
    },
    {
      id: "formatfactory",
      category: "media",
      title: "格式工厂",
      desc: "万能的多媒体格式转换软件。",
      link: "http://www.pcfreetime.com/",
      iconClass: "fas fa-sync-alt",
      tags: ["转换", "视频", "音频"],
      recommendReason: "老牌转换工具，功能全面，操作简单。",
      level: "经典",
    },

    // --- 在线神器 ---
    {
      id: "crontab",
      category: "online",
      title: "Crontab.guru",
      desc: "Cron 表达式在线生成和解释工具。",
      link: "https://crontab.guru/",
      iconClass: "fas fa-clock",
      tags: ["Cron", "运维", "工具"],
      recommendReason: "再也不用担心写错Cron表达式了，直观易懂。",
      level: "实用",
    },
    {
      id: "caniuse",
      category: "online",
      title: "Can I use",
      desc: "前端浏览器兼容性查询网站。",
      link: "https://caniuse.com/",
      iconClass: "fab fa-chrome",
      tags: ["前端", "兼容性", "查询"],
      recommendReason: "前端开发必查，看看你的CSS/JS特性支持哪些浏览器。",
      level: "必备",
    },
    {
      id: "processon",
      category: "online",
      title: "ProcessOn",
      desc: "免费在线作图，实时协作。支持流程图、思维导图等。",
      link: "https://www.processon.com/",
      iconClass: "fas fa-project-diagram",
      tags: ["绘图", "思维导图", "流程图"],
      recommendReason: "在线画图很方便，模板丰富，支持团队协作。",
      level: "常用",
    },
  ],
};
